name: Laravel Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: desejo_livre_test_db
          POSTGRES_USER: desejo_livre_test_user
          POSTGRES_PASSWORD: desejo_livre_test_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v5

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, pdo_pgsql, pgsql, redis, gd, zip
        coverage: none

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Clear Composer Cache
      run: composer clear-cache

    - name: Install Dependencies
      run: |
        composer install --no-interaction --prefer-dist --optimize-autoloader
        composer dump-autoload --optimize

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database
      run: |
        php artisan migrate --force
        php artisan db:seed --force
      env:
        DB_CONNECTION: pgsql
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
        DB_DATABASE: desejo_livre_test_db
        DB_USERNAME: desejo_livre_test_user
        DB_PASSWORD: desejo_livre_test_password
        REDIS_HOST: 127.0.0.1
        REDIS_PORT: 6379
        SCOUT_DRIVER: null
        CACHE_STORE: redis
        QUEUE_CONNECTION: sync

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit
      env:
        DB_CONNECTION: pgsql
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
        DB_DATABASE: desejo_livre_test_db
        DB_USERNAME: desejo_livre_test_user
        DB_PASSWORD: desejo_livre_test_password
        REDIS_HOST: 127.0.0.1
        REDIS_PORT: 6379
        SCOUT_DRIVER: null
        CACHE_STORE: redis
        QUEUE_CONNECTION: sync
